class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'アイスランド共和国 Iceland ' }, { id: 3, name: 'アイルランド Ireland' }, { id: 4, name: 'アゼルバイジャン共和国 Azerbaijan ' },
    { id: 5, name: 'アフガニスタン Afghanistan' }, { id: 6, name: 'アメリカ合衆国 United States of America' }, { id: 7, name: 'アラブ首長国連邦 United Arab Emirates' },
    { id: 8, name: 'アルジェリア民主人民共和国 Algeria ' }, { id: 9, name: 'アルゼンチン共和国 Argentina' }, { id: 10, name: 'アルバニア共和国 Albania' },
    { id: 11, name: 'アルメニア共和国 Armenia' }, { id: 12, name: 'アンゴラ共和国 Angola' }, { id: 13, name: 'アンティグア・バーブーダ Antigua and Barbuda' },
    { id: 14, name: 'アンドラ Andorra' }, { id: 15, name: 'イエメン共和国 Yemen' }, { id: 16, name: 'イスラエル国 Israel' },
    { id: 17, name: 'イタリア共和国 Italy' }, { id: 18, name: 'イラク共和国 Iraq' }, { id: 19, name: 'イラン・イスラム共和国 Iran' },
    { id: 20, name: 'インド India' }, { id: 21, name: 'インドネシア共和国 Indonesia' }, { id: 22, name: 'ウガンダ共和国 Uganda' },
    { id: 23, name: 'ウクライナ Ukraine' }, { id: 24, name: 'ウズベキスタン共和国 Uzbekistan' }, { id: 25, name: 'ウルグアイ東方共和国 Uruguay' },
    { id: 26, name: 'エクアドル共和国 Ecuador' }, { id: 27, name: 'エジプト・アラブ共和国 Egypt' }, { id: 28, name: 'エストニア共和国 Estonia' },
    { id: 29, name: 'エスワティニ王国 Eswatini' }, { id: 30, name: 'エチオピア連邦民主共和国 Ethiopia' }, { id: 31, name: 'エリトリア国 Eritrea' },
    { id: 32, name: 'エルサルバドル共和国 El Salvador' }, { id: 33, name: 'オーストラリア連邦 Australia' }, { id: 34, name: 'オーストリア共和国 Austria' },
    { id: 35, name: 'オマーン国 Oman ' }, { id: 36, name: 'オランダ王国 Netherlands' }, { id: 37, name: 'ガーナ共和国 Ghana ' },
    { id: 38, name: 'カーボヴェルデ共和国 Cabo Verde' }, { id: 39, name: 'ガイアナ共和国 Guyana ' }, { id: 40, name: 'カザフスタン共和国 Kazakhstan' },
    { id: 41, name: 'カタール国 Qatar ' }, { id: 42, name: 'カナダ Canada' }, { id: 43, name: 'ガボン共和国 Gabon' },
    { id: 44, name: 'カメルーン共和国 Cameroon ' }, { id: 45, name: 'ガンビア共和国 Gambia' }, { id: 46, name: 'カンボジア王国 Cambodia' },
    { id: 47, name: '北マケドニア共和国 Republic of North Macedonia ' }, { id: 48, name: 'ギニアビサウ共和国 Guinea-Bissau' }, { id: 49, name: 'ギニア共和国 Guinea ' },
    { id: 50, name: 'キプロス共和国 Cyprus' }, { id: 51, name: 'キューバ共和国 Cuba' }, { id: 52, name: 'ギリシャ共和国 Greece' },
    { id: 53, name: 'キリバス共和国 Kiribati ' }, { id: 54, name: 'キルギス共和国 Kyrgyzstan' }, { id: 55, name: 'グアテマラ共和国 Guatemala' },
    { id: 56, name: 'クウェート国 Kuwait' }, { id: 57, name: 'クック諸島 Cook Islands' }, { id: 58, name: 'グレート・ブリテン及び北部アイルランド連合王国 United Kingdom' },
    { id: 59, name: 'グレナダ Grenada' }, { id: 60, name: 'クロアチア共和国 Croatia' }, { id: 61, name: 'ケニア共和国 Kenya' },
    { id: 62, name: "コートジボワール共和国 Cote d'Ivoire" }, { id: 63, name: 'コスタリカ共和国 Costa Rica ' }, { id: 64, name: 'コモロ連合 Comoros' },
    { id: 65, name: 'コロンビア共和国 Colombia' }, { id: 66, name: 'コンゴ共和国 Congo' }, { id: 67, name: 'コンゴ民主共和国 Democratic Republic of Congo' },
    { id: 68, name: 'サウジアラビア王国 Saudi Arabia' }, { id: 69, name: 'サモア独立国 Samoa ' }, { id: 70, name: 'サントメ・プリンシペ民主共和国 Sao Tome and Principe' },
    { id: 71, name: 'ザンビア共和国 Zambia' }, { id: 72, name: 'サンマリノ共和国 San Marino' }, { id: 73, name: 'シエラレオネ共和国 Sierra Leone' },
    { id: 74, name: 'ジブチ共和国 Djibouti' }, { id: 75, name: 'ジャマイカ Jamaica' }, { id: 76, name: 'ジョージア Georgia' },
    { id: 77, name: 'シリア・アラブ共和国 Syrian Arab Republic' }, { id: 78, name: 'シンガポール共和国 Singapore' }, { id: 79, name: 'ジンバブエ共和国 Zimbabwe' },
    { id: 80, name: 'スイス連邦 Switzerland' }, { id: 81, name: 'スウェーデン王国 Sweden' }, { id: 82, name: 'スーダン共和国 Sudan' },
    { id: 83, name: 'スペイン Spain' }, { id: 84, name: 'スリナム共和国 Suriname' }, { id: 85, name: 'スリランカ民主社会主義共和国 Sri Lanka' },
    { id: 86, name: 'スロバキア共和国 Slovakia' }, { id: 87, name: 'スロベニア共和国 Slovenia' }, { id: 88, name: 'セーシェル共和国 Seychelles' },
    { id: 89, name: '赤道ギニア共和国 Equatorial Guinea' }, { id: 90, name: 'セネガル共和国 Senegal' }, { id: 91, name: 'セルビア共和国 Republic of Serbia' },
    { id: 92, name: 'セントクリストファー・ネーヴィス Saint Kitts and Nevis' }, { id: 93, name: 'セントビンセントおよびグレナディーン諸島 Saint Vincent and the Grenadines' }, { id: 94, name: 'セントルシア Saint Lucia' },
    { id: 95, name: 'ソマリア連邦共和国 Somalia' }, { id: 96, name: 'ソロモン Solomon Islands' }, { id: 97, name: 'タイ王国 Thailand' },
    { id: 98, name: '大韓民国 Republic of Korea' }, { id: 99, name: 'タジキスタン共和国 Tajikistan' }, { id: 100, name: 'タンザニア連合共和国 United Republic of Tanzania' },
    { id: 101, name: 'チェコ共和国 Czechia' }, { id: 102, name: 'チャド共和国 Chad' }, { id: 103, name: '中央アフリカ共和国 Central African Republic' },
    { id: 104, name: '中華人民共和国 China' }, { id: 105, name: 'チュニジア共和国 Tunisia' }, { id: 106, name: 'チリ共和国 Chile' },
    { id: 107, name: 'ツバル Tuvalu' }, { id: 108, name: 'デンマーク王国 Denmark' }, { id: 109, name: 'ドイツ連邦共和国 Germany' },
    { id: 110, name: 'トーゴ共和国 Togo' }, { id: 111, name: 'ドミニカ共和国 Dominican Republic' }, { id: 112, name: 'ドミニカ国 Dominica' },
    { id: 113, name: 'トリニダード・トバゴ共和国 Trinidad and Tobago' }, { id: 114, name: 'トルクメニスタン Turkmenistan ' }, { id: 115, name: 'トルコ共和国 Turkey' },
    { id: 116, name: 'トンガ王国 Tonga' }, { id: 117, name: 'ナイジェリア連邦共和国 Nigeria' }, { id: 118, name: 'ナウル共和国 Nauru' },
    { id: 119, name: 'ナミビア共和国 Namibia ' }, { id: 120, name: 'ニウエ Niue' }, { id: 121, name: 'ニカラグア共和国 Nicaragua ' },
    { id: 122, name: 'ニジェール共和国 Niger' }, { id: 123, name: '日本国 Japan' }, { id: 124, name: 'ニュージーランド New Zealand' },
    { id: 125, name: 'ネパール連邦民主共和国 Nepal' }, { id: 126, name: 'ノルウェー王国 Norway' }, { id: 127, name: 'バーレーン王国 Bahrain' },
    { id: 128, name: 'ハイチ共和国 Haiti' }, { id: 129, name: 'パキスタン・イスラム共和国 Pakistan' }, { id: 130, name: 'バチカン市国 Holy See' },
    { id: 131, name: 'パナマ共和国 Panama' }, { id: 132, name: 'バヌアツ共和国 Vanuatu' }, { id: 133, name: 'バハマ国 Bahamas' },
    { id: 134, name: 'パプアニューギニア独立国 Papua New Guinea' }, { id: 135, name: 'パラオ共和国 Palau' }, { id: 136, name: 'パラグアイ共和国 Paraguay' },
    { id: 137, name: 'バルバドス Barbados' }, { id: 138, name: 'ハンガリー Hungary' }, { id: 139, name: 'バングラデシュ人民共和国 Bangladesh' },
    { id: 140, name: '東ティモール民主共和国 Timor-Leste ' }, { id: 141, name: 'フィジー共和国 Fiji' }, { id: 142, name: 'フィリピン共和国 Philippines' },
    { id: 143, name: 'フィンランド共和国 Finland' }, { id: 144, name: 'ブータン王国 Bhutan' }, { id: 145, name: 'ブラジル連邦共和国 Brazil' },
    { id: 146, name: 'フランス共和国 France' }, { id: 147, name: 'ブルガリア共和国 Bulgaria' }, { id: 148, name: 'ブルキナファソ Burkina Faso' },
    { id: 149, name: 'ブルネイ・ダルサラーム国 Brunei Darussalam' }, { id: 150, name: 'ブルンジ共和国 Burundi ' }, { id: 151, name: 'ベトナム社会主義共和国 Viet Nam' },
    { id: 152, name: 'ベナン共和国 Benin ' }, { id: 153, name: 'ベネズエラ・ボリバル共和国 Venezuela' }, { id: 154, name: 'ベラルーシ共和国 Belarus' },
    { id: 155, name: 'ベリーズ Belize' }, { id: 156, name: 'ペルー共和国 Peru' }, { id: 157, name: 'ベルギー王国 Belgium' },
    { id: 158, name: 'ポーランド共和国 Poland ' }, { id: 159, name: 'ボスニア・ヘルツェゴビナ Bosnia and Herzegovina ' }, { id: 160, name: 'ボツワナ共和国 Botswana ' },
    { id: 161, name: 'ボリビア多民族国 Bolivia ' }, { id: 162, name: 'ポルトガル共和国 Portugal' }, { id: 163, name: 'ホンジュラス共和国 Honduras' },
    { id: 164, name: 'マーシャル諸島共和国 Marshall Islands' }, { id: 165, name: 'マダガスカル共和国 Madagascar' }, { id: 166, name: 'マラウイ共和国 Malawi' },
    { id: 167, name: 'マリ共和国 Mali' }, { id: 168, name: 'マルタ共和国 Malta ' }, { id: 169, name: 'マレーシア Malaysia' },
    { id: 170, name: 'ミクロネシア連邦 Micronesia (Federated States of)' }, { id: 171, name: '南アフリカ共和国 South Africa' }, { id: 172, name: '南スーダン共和国 South Sudan' },
    { id: 173, name: 'ミャンマー連邦共和国 Myanmar' }, { id: 174, name: 'メキシコ合衆国 Mexico ' }, { id: 175, name: 'モーリシャス共和国 Mauritius' },
    { id: 176, name: 'モーリタニア・イスラム共和国 Mauritania' }, { id: 177, name: 'モザンビーク共和国 Mozambique' }, { id: 178, name: 'モナコ公国 Monaco ' },
    { id: 179, name: 'モルディブ共和国 Maldives' }, { id: 180, name: 'モルドバ共和国 Republic of Moldova' }, { id: 181, name: 'モロッコ王国 Morocco' },
    { id: 182, name: 'モンゴル国 Mongolia ' }, { id: 183, name: 'モンテネグロ Montenegro ' }, { id: 184, name: 'ヨルダン・ハシェミット王国 Jordan ' },
    { id: 185, name: "ラオス人民民主共和国 Lao People's Democratic Republic" }, { id: 186, name: 'ラトビア共和国 Latvia L' }, { id: 187, name: 'リトアニア共和国 Lithuania' },
    { id: 188, name: 'リビア Libya' }, { id: 189, name: 'リヒテンシュタイン公国 Liechtenstein ' }, { id: 190, name: 'リベリア共和国 Liberia ' },
    { id: 191, name: 'ルーマニア Romania' }, { id: 192, name: 'ルクセンブルク大公国 Luxembourg' }, { id: 193, name: 'ルワンダ共和国 Rwanda ' },
    { id: 194, name: 'レソト王国 Lesotho ' }, { id: 195, name: 'レバノン共和国 Lebanon' }, { id: 196, name: 'ロシア連邦 Russian Federation ' }

  ]
  include ActiveHash::Associations
  has_many :tweets
end
